### ISSUE TITLE
Plugin throws error

### ISSUE THREAD

**Issue by xichengliudui** [songjiayang/nginx-log-exporter#2]
hello，i'm using nginx-log-exporter
execute: `./nginx-log-exporter  &`
erroe
```
[2] 72717
[root@registry nginx-log-exporter]# panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7caf2b]

goroutine 1 [running]:
github.com/songjiayang/nginx-log-exporter/config.(*AppConfig).DynamicLabels(...)
	/Golang/nginx-log-exporter/config/config.go:41
github.com/songjiayang/nginx-log-exporter/collector.NewCollector(0xc000140370, 0xa)
	/Golang/nginx-log-exporter/collector/log_collector.go:33 +0x9b
main.main()
	/Golang/nginx-log-exporter/main.go:30 +0x21f
```

**Comment by xichengliudui** [comment]
my config.yml
```
- name: app
  format: $remote_addr - $remote_user [$time_local] "$method $request $protocol" $request_time-$upstream_response_time $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"
  source_files:
    - /opt/nginx/log/access.log
```

**Comment by patsevanton** [comment]
Same error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7ffae8]

goroutine 1 [running]:
github.com/songjiayang/nginx-log-exporter/config.(*AppConfig).DynamicLabels(...)
	/root/go/src/github.com/songjiayang/nginx-log-exporter/config/config.go:41
github.com/songjiayang/nginx-log-exporter/collector.NewCollector(0xc00010a320, 0xa)
	/root/go/src/github.com/songjiayang/nginx-log-exporter/collector/log_collector.go:32 +0x88
main.main()
	/root/go/src/github.com/songjiayang/nginx-log-exporter/main.go:30 +0x21c
```

config.yml:
```
- name: app
  format: $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" $request_time $upstream_response_time $pipe $upstream_addr "$cookie_JSESSIONID" $msec
  source_files:
    - /var/log/nginx/access.log
```
