### ISSUE TITLE
Issue with exemplars 

### ISSUE THREAD

**Issue by frenkye** [songjiayang/nginx-log-exporter#7]
Hi, 
I wanted to test the exemplars part of this exporter, if it would be to our interest, but I have problem to enable this feature.

First I found out the exemplars was added after the 0.2.0 version, so i build from source, but still can't manage to show them on histograms.

Any advice?

```
- name: test
  format: $remote_addr [$time_local] "$method $request $protocol" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_time "$upstream_addr" $upstream_response_time $upstream_cache_status $cookie_SESSID $sent_http_x_request_id request_id=$request_id trace_id=$trace_id
  source_files:
    - ./path/to/log
  relabel_config:
    source_labels:
      - request
      - method
      - status
    replacement:
      request:
        trim: "?"
      status:
        replace:
          - target: 4.+
            value: 4xx
          - target: 5.+
            value: 5xx
  histogram_buckets: [0.1, 0.3, 0.5, 1, 2]
  exemplar_config:
    match:
      request_time: ">= 0.3"
    labels:
      - request_id
      - trace_id
      - remote_addr
```

Log line (is a bit messy but i trying the new fields):
```
192.168.21.1 [07/Mar/2023:13:19:17 +0100] "GET /XXXX HTTP/1.1" 200 122524 "https://referer/XXXX" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0" 3.680 "unix:/var/lib/php/7.4/fpm/name.sock" 3.680 - a7b4j3m1cq205qurit808a9qfk 1c6394284038c167766bfd4ab3b3be72 request_id=1c6394284038c167766bfd4ab3b3be72 trace_id=ef499069fb92418e
```
